### experiments ###
SUB_EXPERIMENT_NAME = 'vgg_cells/test_1'
DATASET_PATH = '../../datasets/vgg_cells'
TRAIN_PATH = f'{DATASET_PATH}/train'
VAL_PATH = f'{DATASET_PATH}/val'
TEST_PATH = f'{DATASET_PATH}/test'
CHECKPOINTS_PATH = f'./{SUB_EXPERIMENT_NAME}/checkpoints'
CHECKPOINT_FILENAME = f'{CHECKPOINTS_PATH}/best_model.hdf5'
QUALITATIVE_RESULTS_PATH = f'./{SUB_EXPERIMENT_NAME}/results/qualitative'
QUANTITATIVE_RESULTS_PATH = f'./{SUB_EXPERIMENT_NAME}/results/quantitative'
LOGS_PATH = f'./{SUB_EXPERIMENT_NAME}/logs/'
LOGS_FILENAME = f'{LOGS_PATH}/logs.json'

### create validation split from initial train data ###
VGG_CELLS_RAND_SEED = 32
VGG_CELLS_VAL_SIZE = 32
CARPK_RAND_SEED = 128
CARPK_VAL_SIZE = 128
SHANGHAI_TECH_PART_B_RAND_SEED = 64
SHANGHAI_TECH_PART_B_VAL_SIZE = 64

RAND_SEED = VGG_CELLS_RAND_SEED
VAL_SIZE = VGG_CELLS_VAL_SIZE

### train ###
LOSS_NAME = 'mean_absolute_error'
DIM = (256, 256, 3)  # VGG Cells
#DIM = (768, 1024, 3) # ShanghaiTech
#DIM = (720, 1280, 3) # CARPK
BATCH_SIZE = 32
EPOCHS = 25
SHUFFLE = True

### ground truth ###
# sigma for density map generation 
SIGMA = 5
VGG_CELLS_SIGMA = SIGMA
CARPK_SIGMA = SIGMA
SHANGHAI_TECH_PART_A_SIGMA = SIGMA
SHANGHAI_TECH_PART_B_SIGMA = SIGMA

GT_SIGMA = VGG_CELLS_SIGMA

DENSITY_MAP_MULTIPLICATION_FACTOR = 100.